# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Fri Apr  6 17:51:03 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(490, 380)
        MainWindow.setMinimumSize(QtCore.QSize(490, 380))
        MainWindow.setMaximumSize(QtCore.QSize(490, 380))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "IP Calculator", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setStatusTip(_fromUtf8(""))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lineEdit_s1 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_s1.setGeometry(QtCore.QRect(70, 15, 40, 20))
        self.lineEdit_s1.setObjectName(_fromUtf8("lineEdit_s1"))
        self.lineEdit_s2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_s2.setGeometry(QtCore.QRect(130, 15, 40, 20))
        self.lineEdit_s2.setObjectName(_fromUtf8("lineEdit_s2"))
        self.lineEdit_s3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_s3.setGeometry(QtCore.QRect(190, 15, 40, 20))
        self.lineEdit_s3.setObjectName(_fromUtf8("lineEdit_s3"))
        self.lineEdit_s4 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_s4.setGeometry(QtCore.QRect(250, 15, 40, 20))
        self.lineEdit_s4.setObjectName(_fromUtf8("lineEdit_s4"))
        self.lineEdit_s5 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_s5.setGeometry(QtCore.QRect(310, 15, 40, 20))
        self.lineEdit_s5.setObjectName(_fromUtf8("lineEdit_s5"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 20, 10, 16))
        self.label.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 20, 10, 13))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 20, 10, 13))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 20, 10, 13))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_m1 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_m1.setGeometry(QtCore.QRect(70, 45, 40, 20))
        self.lineEdit_m1.setObjectName(_fromUtf8("lineEdit_m1"))
        self.lineEdit_m2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_m2.setGeometry(QtCore.QRect(130, 45, 40, 20))
        self.lineEdit_m2.setObjectName(_fromUtf8("lineEdit_m2"))
        self.lineEdit_m3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_m3.setGeometry(QtCore.QRect(190, 45, 40, 20))
        self.lineEdit_m3.setObjectName(_fromUtf8("lineEdit_m3"))
        self.lineEdit_m4 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_m4.setGeometry(QtCore.QRect(250, 45, 40, 20))
        self.lineEdit_m4.setObjectName(_fromUtf8("lineEdit_m4"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(120, 50, 10, 13))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(180, 50, 10, 13))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(240, 50, 10, 13))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 85, 75, 23))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 170, 131, 16))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Network address:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 250, 151, 16))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Broadcast address:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(10, 290, 111, 16))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Network class:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_netAddr = QtGui.QLabel(self.centralwidget)
        self.label_netAddr.setGeometry(QtCore.QRect(160, 170, 311, 16))
        self.label_netAddr.setText(_fromUtf8(""))
        self.label_netAddr.setObjectName(_fromUtf8("label_netAddr"))
        self.label_brodAddr = QtGui.QLabel(self.centralwidget)
        self.label_brodAddr.setGeometry(QtCore.QRect(160, 250, 311, 16))
        self.label_brodAddr.setText(_fromUtf8(""))
        self.label_brodAddr.setObjectName(_fromUtf8("label_brodAddr"))
        self.label_netClass = QtGui.QLabel(self.centralwidget)
        self.label_netClass.setGeometry(QtCore.QRect(220, 290, 181, 20))
        self.label_netClass.setText(_fromUtf8(""))
        self.label_netClass.setObjectName(_fromUtf8("label_netClass"))
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "IP:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Mask:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 81, 16))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Binary IP:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 101, 16))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Binary Mask:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_binIP = QtGui.QLabel(self.centralwidget)
        self.label_binIP.setGeometry(QtCore.QRect(160, 130, 311, 16))
        self.label_binIP.setText(_fromUtf8(""))
        self.label_binIP.setObjectName(_fromUtf8("label_binIP"))
        self.label_binMask = QtGui.QLabel(self.centralwidget)
        self.label_binMask.setGeometry(QtCore.QRect(160, 150, 311, 16))
        self.label_binMask.setText(_fromUtf8(""))
        self.label_binMask.setObjectName(_fromUtf8("label_binMask"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 230, 101, 16))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Binary Mask:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 210, 81, 16))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Binary IP:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_binIP2 = QtGui.QLabel(self.centralwidget)
        self.label_binIP2.setGeometry(QtCore.QRect(160, 210, 311, 16))
        self.label_binIP2.setText(_fromUtf8(""))
        self.label_binIP2.setObjectName(_fromUtf8("label_binIP2"))
        self.label_binMask2 = QtGui.QLabel(self.centralwidget)
        self.label_binMask2.setGeometry(QtCore.QRect(160, 230, 311, 16))
        self.label_binMask2.setText(_fromUtf8(""))
        self.label_binMask2.setObjectName(_fromUtf8("label_binMask2"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 310, 201, 16))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Nr. of effective addresses:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 330, 151, 16))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Nr. of all addresses:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_effAddr = QtGui.QLabel(self.centralwidget)
        self.label_effAddr.setGeometry(QtCore.QRect(220, 310, 81, 16))
        self.label_effAddr.setText(_fromUtf8(""))
        self.label_effAddr.setObjectName(_fromUtf8("label_effAddr"))
        self.label_allAddr = QtGui.QLabel(self.centralwidget)
        self.label_allAddr.setGeometry(QtCore.QRect(220, 330, 81, 16))
        self.label_allAddr.setText(_fromUtf8(""))
        self.label_allAddr.setObjectName(_fromUtf8("label_allAddr"))
        self.label_netAddrDec = QtGui.QLabel(self.centralwidget)
        self.label_netAddrDec.setGeometry(QtCore.QRect(160, 190, 230, 16))
        self.label_netAddrDec.setText(_fromUtf8(""))
        self.label_netAddrDec.setObjectName(_fromUtf8("label_netAddrDec"))
        self.label_brodAddrDec = QtGui.QLabel(self.centralwidget)
        self.label_brodAddrDec.setGeometry(QtCore.QRect(160, 270, 230, 13))
        self.label_brodAddrDec.setText(_fromUtf8(""))
        self.label_brodAddrDec.setObjectName(_fromUtf8("label_brodAddrDec"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

